apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  namespace: usn
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
        - name: ai-service
          image: 912759111826.dkr.ecr.us-east-1.amazonaws.com/usn-ai-service:v1
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
