apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: usn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 912759111826.dkr.ecr.us-east-1.amazonaws.com/usn-frontend:v2
          ports:
            - name: http
              containerPort: 3000
