apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: usn
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: REPLACE_WITH_ROOT_PASSWORD
  MYSQL_USER: usn
  MYSQL_PASSWORD: REPLACE_WITH_APP_PASSWORD
