apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: social-network
type: Opaque
stringData:
  mysql-root-password: "admin"
  mysql-database: "railway"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: social-network
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/railway?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_USERNAME: "root"
