apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: tu-usuario-docker/social-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: social-network
spec:
  type: LoadBalancer # En AWS EKS esto crea automáticamente un Load Balancer público
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: frontend
