apiVersion: batch/v1
kind: Job
metadata:
  name: stress-test-job
  namespace: usn
spec:
  template:
    metadata:
      name: stress-agent
    spec:
      containers:
        - name: stress-agent
          image: curlimages/curl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Iniciando prueba de estres contra backend-service:5000..."
              for i in $(seq 1 500); do
                curl -s http://backend-service:5000/images/defaultProfile.png > /dev/null &
                if [ $(($i % 50)) -eq 0 ]; then
                  echo "Peticiones enviadas: $i / 500"
                  sleep 0.1
                fi
              done
              wait
              echo "Prueba de estres completada."
      restartPolicy: Never
  backoffLimit: 1
