spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/railway}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
  devtools:
    restart:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
file:
  upload-dir: src/main/resources/images
server:
  address: 0.0.0.0
  port: 5000
